apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default (printf "%s-config" .Values.appName) }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}